web/assets/css/styles.min.css:
    - src/assets/css/bootstrap.css
    - src/assets/css/bootstrap-theme.css
    - src/assets/css/flip.css
    - src/assets/css/style.css

web/assets/js/scripts.min.js:
    - src/assets/js/bootstrap.js
    - src/assets/js/script.js
