<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    $vendorDir . '/symfony/intl/Symfony/Component/Intl/Resources/stubs/functions.php',
    $vendorDir . '/herrera-io/json/src/lib/json_version.php',
    $vendorDir . '/herrera-io/phar-update/src/lib/constants.php',
    $vendorDir . '/herrera-io/go/src/lib/functions.php',
    $vendorDir . '/herrera-io/file-system-functions/src/lib/fs_functions.php',
);
